version: "2.1"
services:
  csvapp:
    ports:
      - "9393:9300"
    volumes:
      - /home/anand/Abhishek/csvserver/solution/inputFile:/csvserver/inputdata
    environment:
      - CSVSERVER_BORDER=Orange 
    image: "infracloudio/csvserver"
